server:
  port: 8082
spring:
  application:
    name: api-gateway


eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.138:8081/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.138
    instance-id: ${spring.application.name}:${server.port}

zuul:   #网关
 # prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**
    user-service: /user/**

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms